name: Weekly Email Cron Job

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-emails:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
        
      - name: Run email cron job
        run: node jobs/emailCron.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}